apiVersion: 1
deleteDatasources: []
datasources:
  - access: proxy
    isDefault: true
    name: Prometheus
    type: prometheus
    url: http://prometheus:9090/
  - access: proxy
    isDefault: false
    name: Loki
    type: loki
    url: http://loki:3100
